package hr.fer.zemris.java.custom.scripting.lexer.demo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import hr.fer.zemris.java.custom.scripting.lexer.LexerException;
import hr.fer.zemris.java.custom.scripting.lexer.LexerState;
import hr.fer.zemris.java.custom.scripting.lexer.SmartScriptLexer;
import hr.fer.zemris.java.custom.scripting.lexer.Token;
import hr.fer.zemris.java.custom.scripting.lexer.TokenType;

/**
 * This program tests SmartSckriptLexer. User can input text and program outputs all tokens 
 * generated by a lexer. When user inputs "kraj" program ends.
 * @author bruno
 */
public class LexerDemo {

	public static void main(String[] args) throws IOException {
		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		
		String row = null;

		while (true) {
			try {
				//System.out.print("> ");
				row = reader.readLine();

				if (row.equals("kraj")) break;

				SmartScriptLexer lexer = new SmartScriptLexer(row);
				lexer.setState(LexerState.TEXT);
				while (true) {
					Token tk = lexer.nextToken();
					printToken(tk);
					if (tk.getType() == TokenType.EOF) break;
					else if (tk.getType() == TokenType.TAG_START) {
						lexer.setState(LexerState.TAG);
					}
					else if (tk.getType() == TokenType.TAG_END) {
						lexer.setState(LexerState.TEXT);
					}
					else if (tk.getType() == TokenType.SYMBOL && 
							tk.getValue() == Character.valueOf('"')) {
						if (lexer.getState() == LexerState.STRING) {
							lexer.setState(LexerState.TAG);
						}
						else {
							lexer.setState(LexerState.STRING);
						}
					}
				}
			} catch(LexerException ex) {
				System.out.println(ex.getMessage());
			}
		}
				
	}
	
	/**
	 * Prints token in format $TokenType "#TokenValue"
	 */
	public static void printToken(Token tk) {
		System.out.println(
				tk.getType().toString() + " " + 
				(tk.getValue() == null ? "null" : "\"" + tk.getValue().toString() + "\"")
		);
	}

}
